# Server
server:
  port: 8763
 
#spring
spring: 
  data: 
    mongodb: 
      uri: mongodb://bapuser:bapuser123@mongo:27017/amcloud
      database: amcloud
  rabbitmq: 
    publisher-confirms: true
    publisher-returns: true
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: AUTO   

#cxf
cxf: 
  path: /api/soap

#ws
ws: 
  equipservice:
    resturl: http://amcloud-zuul:8769/api/rest/service
  allowjumprest: true
      
#日志过期时间设置
expirerule:
  dataLogExpireDay: 90
  errorLogExpireDay: 60

#httpclient
httpclient: 
  config: 
    proxy: false
    proxyhost:
    proxyPort: 8080
    maxConnTotal: 2000  
    maxPerRoute: 1000  
    connectTimeout: 60000
    connectRequestTimeout: 30000
    socketTimeout: 180000

eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}

security:
  user:
    name: user
    password: password
  basic: 
    enabled: false
management:
  security:
    enabled: false
