# Server
server:
  port: 8766
 
#spring
spring: 
  data: 
    mongodb: 
      uri: mongodb://bapuser:bapuser123@192.168.4.121:27017/amcloud
      database: amcloud

#eureka
eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}

security:
  user:
    name: user
    password: password
  basic: 
    enabled: false
management:
  security:
    enabled: false

#httpclient
httpclient: 
  config: 
    connectTimeout: 10000
    connectRequestTimeout: 10000
    socketTimeout: 3000000

#日志过期时间设置
expirerule:
  dataLogExpireDay: 1
  errorLogExpireDay: 1
